### ISSUE TITLE
example can not run

### ISSUE THREAD

**Issue by felixfan** [cancerdatasci/demeter#1]
step 1: it looks the 'header' in batches.csv is different from 'preprocess-gcts'
step 2: no 'data' folder
Please test all steps and provide necessary files so other people can use it.

**Comment by pgm** [comment]
I'll take a look at this and update the README with corrections.

**Comment by pgm** [comment]
I've just pushed an updated README with corrections and fixed the old test data files which had the wrong header.  

Also, I've added the literal commands that can be used to re-run on the data available from the Achilles portal which is a more realistic example than the tiny test files included in the repo.

Please let me know if you encounter any additional problems.

Thanks
Phil
