### ISSUE TITLE
run-eval-for-each file?

### ISSUE THREAD

**Issue by stevemmarshall** [cancerdatasci/demeter#2]
Hi

I'm going through your readme to try and run the example process but I can't seem to find the run-eval-for-each file... I assume it's a simple little bash script?

thanks
steve

**Comment by pgm** [comment]
You're right, that was missing from to the repository. (It only recently got introduced when I tried to improve the documentation in the README file.)

Regardless, I've added the missing run-eval-for-each script to the repo, so this should be resolved now.

Thanks for letting me know.
